Added a new menu for character control
saber-nyan/ddlc-android pull request #16
Opened 2018-01-13 23:58 UTC by AlexAzumi

With this menu now is possible to take control of the persistent data. The player can "delete" the four characters and even restore them.

2018-01-14 08:49 UTC, saber-nyan reviewed
Many thanks for this screen, constantly there was not enough time to do it.

But is not it better to do the same thing as on a PC: give user ability to manually delete `.chr` files by putting them on the first start in `/sdcard/Android/data/ru.saber_nyan.ddlc/files`?

2018-01-14 08:49 UTC, saber-nyan commented on game/screens.rpy
> +            textbutton _("Characters") action [ShowMenu("characters"), SensitiveIf(renpy.get_screen("characters") == None)]
I think we should not show this button immediately after the first start: it will be a small spoiler. It is better to hide it under some condition.

2018-01-14 20:25 UTC, saber-nyan requested changes
Hmm, after clicking on "Characters" from the main menu, I got
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens.rpy", line 913, in execute
    init -501 screen characters() tag menu:
  File "game/screens.rpy", line 913, in execute
    init -501 screen characters() tag menu:
  File "game/screens.rpy", line 914, in execute
    use game_menu(_("Files"), scroll ="viewport"):
  File "game/screens.rpy", line 602, in execute
    init -501 screen game_menu(title, scroll=None):
  File "game/screens.rpy", line 602, in execute
    init -501 screen game_menu(title, scroll=None):
  File "game/screens.rpy", line 613, in execute
    frame:
  File "game/screens.rpy", line 616, in execute
    has hbox
  File "game/screens.rpy", line 622, in execute
    frame:
  File "game/screens.rpy", line 625, in execute
    if scroll == "viewport":
  File "game/screens.rpy", line 627, in execute
    viewport:
  File "game/screens.rpy", line 635, in execute
    has vbox
  File "game/screens.rpy", line 636, in execute
    transclude
  File "game/screens.rpy", line 914, in execute
    use game_menu(_("Files"), scroll ="viewport"):
  File "game/screens.rpy", line 915, in execute
    vbox:
  File "game/screens.rpy", line 918, in execute
    frame:
  File "game/screens.rpy", line 923, in execute
    vbox:
  File "game/screens.rpy", line 929, in execute
    python:
  File "game/screens.rpy", line 930, in <module>
    monika_flag = check_if_exist("monika")
NameError: name 'check_if_exist' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in <module>
    ui.interact()
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\display\core.py", line 2565, in interact
    scene_lists.replace_transient()
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\display\core.py", line 831, in replace_transient
    self.remove(layer, tag)
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\display\core.py", line 1120, in remove
    self.hide_or_replace(layer, remove_index, "hide")
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\display\core.py", line 1044, in hide_or_replace
    d = oldsle.displayable._hide(now - st, now - at, prefix)
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\display\screen.py", line 445, in _hide
    self.update()
  File "D:\DEVELOPMENT_IS_MY_LAIFU\RenPy\renpy\display\screen.py", line 580, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 913, in execute
    init -501 screen characters() tag menu:
  File "game/screens.rpy", line 913, in execute
    init -501 screen characters() tag menu:
  File "game/screens.rpy", line 914, in execute
    use game_menu(_("Files"), scroll ="viewport"):
  File "game/screens.rpy", line 602, in execute
    init -501 screen game_menu(title, scroll=None):
  File "game/screens.rpy", line 602, in execute
    init -501 screen game_menu(title, scroll=None):
  File "game/screens.rpy", line 613, in execute
    frame:
  File "game/screens.rpy", line 616, in execute
    has hbox
  File "game/screens.rpy", line 622, in execute
    frame:
  File "game/screens.rpy", line 625, in execute
    if scroll == "viewport":
  File "game/screens.rpy", line 627, in execute
    viewport:
  File "game/screens.rpy", line 635, in execute
    has vbox
  File "game/screens.rpy", line 636, in execute
    transclude
  File "game/screens.rpy", line 914, in execute
    use game_menu(_("Files"), scroll ="viewport"):
  File "game/screens.rpy", line 915, in execute
    vbox:
  File "game/screens.rpy", line 918, in execute
    frame:
  File "game/screens.rpy", line 923, in execute
    vbox:
  File "game/screens.rpy", line 929, in execute
    python:
  File "game/screens.rpy", line 930, in <module>
    monika_flag = check_if_exist("monika")
NameError: name 'check_if_exist' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Doki Doki Literature Club! 1.1.0
```

Where did you get this method from?
![image](https://user-images.githubusercontent.com/25345196/34920327-2e2da18e-f982-11e7-93aa-08bb160908ee.png)

2018-01-14 20:43 UTC, AlexAzumi commented
Sorry, I accidentally forgot to push "definitions.rpy" file.

2018-01-14 20:49 UTC, saber-nyan commented
Aww, I pushed old piece of code...

2018-01-14 20:57 UTC, saber-nyan commented
https://github.com/saber-nyan/ddlc-android/blob/ced637e25e745351adca48834f255b1b93de0ec9/game/script-ch30.rpy#L311-L319
Now we need to rewrite some of Monica's replicas. Search for the keyword "steam".

2018-01-14 21:03 UTC, saber-nyan commented
By the way, while deleting `.chr` files, the user sees new files ~~created~~ copied by the game: for example, `iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii.txt` or `hxppy thxughts.png`. This is the idea of the developer.

I think it would be nice to do something like that.

2018-01-14 21:13 UTC, AlexAzumi commented
That's a good idea, but, if we want to give the best experience, we have to modify the character control, without using persistent data, and creating the `.chr` in the game's folder.

2018-01-14 21:23 UTC, saber-nyan approved these changes

2018-01-16 17:32 UTC, saber-nyan commented
🤔

2018-01-16 18:43 UTC, saber-nyan commented
So, i merge this PR.

2018-01-16 18:45 UTC, merged

2018-01-26 14:14 UTC, xa0082249956 commented
It could be awesome if I could remove Monika.chr before the first start. You may know there's an easter egg (or not) there.

Sorry for incorrect English grammar.

2018-01-26 14:26 UTC, saber-nyan commented
Hmm, I think we can implement this easter egg with, for example, a few specific gestures in the main game menu.

2018-06-22 05:20 UTC, cimo95 commented
btw where can i put the text file such as poemwords.txt, CAN YOU HEAR ME.txt ?

2025-06-25 02:38 UTC, macartoon commented
Saber-nyan, can you please continue updating this? I love the game and would like to have a way to get an apk with character deletion from the start of the game